### ISSUE TITLE
training data elevation

### ISSUE THREAD

**Issue by fefespn** [justimyhxu/GRM#11]
Hey,
 Thanks for open the weights !! 

I am trying to inference the model with 4 input rendered images from me.
The rendering is from dififrent elevation other than 20, like 7,5,12,25 elevation.
the gaussian I get is not 100 aligned ! 
so do you think it wikll work with 4 diffirent elevation with 4 images ? 
because all the examples from the diffusion models is with +- similar elevation of 20.

in Experiemnt you wrote:
"Following [46], we filter 100k high-quality objects, and render 32 images at
random viewpoints with a fixed 50◦ field of view under ambient lighting."

so the random is with elevation ? do you train with 4 diffirent elevation in the same sample ?  

thanks a lot.

**Comment by justimyhxu** [comment]
Which model have you tried for your inputs?
The grm_r.pth can handle different evevation angels.

**Comment by fefespn** [comment]
thanks a lot, didn't pay attention to that ! grm_random worked fine thanks
